!> @brief Qt-style demo application showcasing ForGE Qt tooling
!> @details Demonstrates signals/slots, resources, UI compilation, and translations
!> @author ForGE Contributors
!> @date 2025

program qt_demo
    use forge_qobject
    use forge_widgets
    use forge_app
    use forge_signals
    implicit none

    type(forge_application) :: app
    type(main_window) :: window

    ! Initialize application
    call app%init()
    call app%set_application_name("Qt Demo")
    call app%set_application_version("1.0.0")

    ! Create main window
    call window%init()
    call window%set_window_title("ForGE Qt Demo")
    call window%resize(600, 400)

    ! Setup UI (would be generated by uic in real usage)
    call window%setup_ui()

    ! Show window
    call window%show()

    ! Run application event loop
    call app%exec()

end program qt_demo

!> @brief Main window with Qt-style features
type, extends(forge_mainwindow) :: main_window
    ! Q_OBJECT  ! This would be processed by moc

    ! UI elements
    type(forge_button) :: click_button
    type(forge_label) :: status_label
    type(forge_checkbox) :: toggle_checkbox

    ! Signals
    type(signal_void) :: button_clicked_signal
    type(signal_string) :: status_changed_signal

    ! Slots
    type(slot_void_proc) :: on_button_clicked_proc
    type(slot_string_proc) :: on_status_changed_proc

contains
    procedure :: setup_ui
    procedure :: on_button_clicked
    procedure :: on_status_changed
end type main_window

subroutine setup_ui(this)
    class(main_window), intent(inout) :: this
    type(forge_layout) :: layout

    ! Initialize UI elements
    call this%click_button%init()
    call this%click_button%set_text("Click Me!")
    call this%click_button%set_object_name("clickButton")

    call this%status_label%init()
    call this%status_label%set_text("Ready")
    call this%status_label%set_object_name("statusLabel")

    call this%toggle_checkbox%init()
    call this%toggle_checkbox%set_text("Enable feature")
    call this%toggle_checkbox%set_object_name("toggleCheckbox")

    ! Setup layout
    call layout%init()
    call layout%add_widget(this%click_button)
    call layout%add_widget(this%status_label)
    call layout%add_widget(this%toggle_checkbox)
    call this%set_layout(layout)

    ! Connect signals and slots
    ! In real usage, these would be auto-generated by moc
    call this%button_clicked_signal%connect(this%on_button_clicked_proc)
    call this%status_changed_signal%connect(this%on_status_changed_proc)

    ! Connect button signal to slot
    call this%click_button%clicked%connect(this%on_button_clicked_proc)

end subroutine setup_ui

subroutine on_button_clicked(this)
    class(main_window), intent(inout) :: this

    ! Update status
    call this%status_label%set_text("Button clicked!")

    ! Emit custom signal
    call this%button_clicked_signal%emit()

end subroutine on_button_clicked

subroutine on_status_changed(this, new_status)
    class(main_window), intent(inout) :: this
    character(len=*), intent(in) :: new_status

    ! Handle status change
    write(*,*) "Status changed to: ", trim(new_status)

end subroutine on_status_changed