name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake libcairo2-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DFORGE_BUILD_SHARED=ON -DFORGE_BUILD_EXAMPLES=ON -DFORGE_BUILD_TESTS=ON -DFORGE_BACKEND_CUSTOM=ON

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    - name: Install
      run: |
        cd build
        make install

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-cairo

    - name: Configure CMake
      shell: msys2 {0}
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DFORGE_BUILD_SHARED=ON -DFORGE_BUILD_EXAMPLES=ON -DFORGE_BUILD_TESTS=ON -DFORGE_BACKEND_CUSTOM=ON

    - name: Build
      shell: msys2 {0}
      run: |
        cd build
        mingw32-make -j$(nproc)

    - name: Test
      shell: msys2 {0}
      run: |
        cd build
        ctest --output-on-failure

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install gcc cmake cairo

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DFORGE_BUILD_SHARED=ON -DFORGE_BUILD_EXAMPLES=ON -DFORGE_BUILD_TESTS=ON -DFORGE_BACKEND_CUSTOM=ON

    - name: Build
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

  fpm-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install FPM
      run: |
        wget https://github.com/fortran-lang/fpm/releases/download/v0.9.0/fpm-0.9.0-linux-x86_64 -O fpm
        chmod +x fpm
        sudo mv fpm /usr/local/bin/

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran

    - name: Build with FPM
      run: fpm build

    - name: Test with FPM
      run: fpm test